### DISCUSSION TITLE
Unable to access a published API

### DISCUSSION THREAD

**Discussion by crjones** [kubeshop/kusk-gateway#640] [General]
I’m giving Kusk a whirl and I was able to seemingly install all of the components successfully. I’m able to launch the dashboard, add APIs and publish them, however, I’m unable to load them up. I have enabled mocking on them. 

It’s important to note that I’m using ClusterIPs across the board and port-forwarding. It’s by way of port-forwarding that I’m trying to hit the mocked endpoint. Do we need to use a LoadBalancer service type instead?

**Comment by crjones** [comment]
Ideally you should set EnvoyFleet service to LoadBalancer instead of ClusterIP.

```yaml
apiVersion: gateway.kusk.io/v1alpha1
kind: EnvoyFleet
metadata:
  name: default
  namespace: default
spec:
  image: "envoyproxy/envoy-alpine:v1.20.0"
  service:
    type: LoadBalancer
    ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: http
  resources:
    requests:
      cpu: 10m
      memory: 100M
  size: 1
  accesslog:
    format: text
    text_template: |
      "[%START_TIME%]" "%REQ(:METHOD)%" "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%" "%RESPONSE_CODE%" "%DURATION%"
    json_template:
      start_time: "%START_TIME%"
      method: "%REQ(:METHOD)%"
      path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
      response_code: "%RESPONSE_CODE%"
      duration: "%DURATION%"
```

More information can be found here: https://docs.kusk.io/reference/customresources/envoyfleet
