### ISSUE TITLE
Create a command to deploy frontend applications in Kubernetes

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#1011]
Would be cool if we enabled frontend developers to deploy their containerized web applications simply with Kusk. 

A command like 

```sh
kusk deploy pages --container dockerhub/containername
```

Under the hood it would create a deployment and expose it 

```sh 
kubectl create deployment web-app --image=usernameweb-application
kubectl expose deployment web-app --name web-app-svc --port=3000
```

and then it would create a simple StaticRoute and connect it: 

```yaml
apiVersion: gateway.kusk.io/v1alpha1
kind: StaticRoute
metadata:
  name: web-app-static-route
spec:
  fleet:
    name: kusk-gateway-envoy-fleet
    namespace: kusk-system
  upstream:
    service:
      name: web-app-svc
      namespace: default
      port: 3000
```

Alternatively, if that's complicated, we could just create the StaticRoute given a service name: 

```sh
kusk deploy pages --service web-app 
```

Which would create the StaticRoute under-the-hood.
