### ISSUE TITLE
Option to keep x-kusk separated in API Custom Resource

### ISSUE THREAD

**Issue by Tarick** [kubeshop/kusk-gateway#136]
**Describe the enhancement you'd like to see**

x-kusk extension is environmental - it is different for dev, qa, stg, prod, whatever.
People will likely keep their OpenAPI pristine and separate x-kusk extention file somewhere and then merge it. 

Option 1: use *kgw* to support this usecase - merge pristine OpenAPI and x-kusk YAML filel and put the resulting OpenAPI into the *spec* field of API CR.

Option 2: keep x-kusk instructions directly in other field (*x-kusk*?) and then merge it in the Manager. This still involves kgw but only for creating CR and putting the correct docs into the fields. This will attribute to the readability as well (keeping x-kusk separated helps to find out how routing works), editing will be better - you will be changing the correct YAML and not embedded string, however we'll need to double some paths entries for the complex configurations and do double checking if some paths are missing in OpenAPI.

With Option 2 we can even think about pulling OpenAPI document using some URL from the application. This will look like this:

```yaml
apiVersion: gateway.kusk.io/v1alpha1
kind: API
metadata:
  name: api-sample
spec:
  # top level x-kusk extension to configure routes
  x-kusk:
    disabled: false
    hosts: [ "*" ]
    cors:
      origins:
      - "*"
      methods:
      - POST
      - GET
      - OPTIONS
      headers:
      - Content-Type
      credentials: true
      expose_headers:
      - X-Custom-Header1
      max_age: 86200
    upstream:
      service:
        name: api
        namespace: default
        port: 80
    path:
      prefix: /api
      # Strips prefix when forwarding to upstream
      rewrite:
        pattern: "^/api"
        substitution: ""
    # Per path overrides
    paths:
      /pet:
        disabled: true
        post:
          disabled: false
          upstream:
            host:
              hostname: newapi.default.svc.cluster.local
              port: 8080
# OpenAPI file as a ref or spec
  ref: "http://api.default.svc.cluster.local:8080"
  spec: |
  # OpenAPI file here
```
