### ISSUE TITLE
Mocking prototype

### ISSUE THREAD

**Issue by Tarick** [kubeshop/kusk-gateway#14]
Implement the way to mock paths with predefined responses as POC.
E.g. using x-kusk construct:
```yaml
x-kusk:
  mock:
    response: "{ blablabla: true }"
```
