### ISSUE TITLE
EnvoyFleet: set status on correct deployment of all resources

### ISSUE THREAD

**Issue by Tarick** [kubeshop/kusk-gateway#146]
**Describe the enhancement you'd like to see**

EnvoyFleet status.State should be set to Deployed once all created resources successfully deployed - including Service, getting the correct external ip address if this is LoadBalancer type.
Using Events population would be great too - i.e. show what was created in the process and report any errors.

**Comment by aabedraba** [comment]
This is done.

```sh
kubectl describe envoyfleet.gateway.kusk.io -n kusk-system kusk-gateway-envoy-fleet
```

```yaml 
Name:         kusk-gateway-envoy-fleet
...
Status:
  State:  Deployed
...
```
