### ISSUE TITLE
Path override doesn't work

### ISSUE THREAD

**Issue by Tarick** [kubeshop/kusk-gateway#205]
**Describe the bug**

Path overrides on path/method don't work.

**To Reproduce**

With the following config:

```yaml
 paths:
   /todos:
     x-kusk:
          path:
            rewrite:
              pattern: "^/second/"
              substitution: "/"
```

routes for /todos don't show the override.

**Expected behavior**

Present path override.

**Desktop (please complete the following information):**
 - Kube Gateway Version v0.0.0.alpha.2.1.1
