### ISSUE TITLE
autodeploy api based on kubernetes annotation

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#250]
I want to be able to automatically configure kusk-gateway for my service by adding an annotation to it:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kusk-gateway/openapi-url: <path/url to openapi definition>
```

The Kusk operator would detect this label and automatically create and deploy a CRD for the OpenAPI definition at the specified URL or path relative to the service itself. The x-kusk.upstream extension would be generated from the service itself if not already there.

Any existing API for this Service would be replaced.

This would allow me to deploy my API without having to do any further configuration - provided that it exposes its OpenAPI definition - or that this is available at a reachable URL.
