### ISSUE TITLE
Kusk Gateway Support for JWT

### ISSUE THREAD

**Issue by jasmingacic** [kubeshop/kusk-gateway#402]

**Comment by aabedraba** [comment]
We should investigate for either JWT or API Keys. Let's have a discussion about it soon.

**Comment by jasmingacic** [comment]
API Keys are already handled by header auth JWT is something esle.

@mbana do you agree?

**Comment by aabedraba** [comment]
We should really rename "Header auth" to "Custom Auth Upstream" or something of that sorts, because that really reflects what it is. 

But in any case, it is possible to achieve now API Keys through custom upstream... In fact even JWT would be possible to achieve with the same method... 

I was thinking we should have a dedicated auth policy for both JWT and API Keys. Question is which one is first.

**Comment by jasmingacic** [comment]
Refreshing this issue and putting it in our scope.

Essentially we'd have to do something similar to this:
```
x-kusk:
  auth:
    jwt: 
        providers:
          provider1:
            issuer: https://provider1.com
            local_jwks:
              inline_string: PUBLIC-KEY
          provider2:
          issuer: https://provider2.com
          local_jwks:
              inline_string: PUBLIC-KEY
        rules:
        - match:
            prefix: /any
          requires:
            requires_any:
              requirements:
              - provider_name: provider1
              - provider_name: provider2
        - match:
            prefix: /all
          requires:
            requires_all:
              requirements:
              - provider_name: provider1
              - provider_name: provider2
       
...
```

We should adhere how it is done in envoy see below
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter#config-http-filters-jwt-authn

The easy thing is that JWT implementation is very granular and is handled by "prefix" filter.

**Comment by jasmingacic** [comment]
Thinking of this we should maybe do something like 

```
x-kusk:
  auth:
    jwt: 
        providers:
          provider1:
            issuer: https://provider1.com
            local_jwks:
              inline_string: PUBLIC-KEY
          provider2:
          issuer: https://provider2.com
          local_jwks:
              inline_string: PUBLIC-KEY 

```

```
    paths:
      /hello:
     x-kusk:
         jwt:
          rules: | # logical OR  in Envoy terms this would match requires_any
             - provider1 
                provider2
# alternatively for logical AND or in Envoy requires_all 
              - provider1
              - provider2 
              -
```
