### ISSUE TITLE
Docs: Mocking guide has `enabled: true` whilst it should be `enabled: false`

### ISSUE THREAD

**Issue by mbana** [kubeshop/kusk-gateway#478]
`docs/guides/mocking.md`:

```yaml
        patch:
          # Disable for patch
          x-kusk:
            mocking:
              enabled: true
```

Should be

```yaml
        patch:
          # Disable for patch
          x-kusk:
            mocking:
              enabled: false
```
