### ISSUE TITLE
When `auth` and `openapi-path` are both defined, the public openapi needs auth to be accessed 

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#519]
I believe the public openapi path would either be public or if it needs to put behind auth, it should be explicit in the openapi definition. 

Perhaps:

We go from 

```yaml
  openapi-path: openapi.yaml
```

to 

```yaml
exposed-openapi: 
	path: openapi.yaml
	public: true
```

??
