### ISSUE TITLE
x-kusk: allow user to specify upstream (backend) in a user-friendly way

### ISSUE THREAD

**Issue by dobegor** [kubeshop/kusk-gateway#52]
We should allow user to specify upstream (backend?) in a few ways:
1. Native Kubernetes Service Name, Namespace and port, i.e.:
```yaml
backend:
  service:
    name: petstore
    namespace: default
    port: http
```
2. Fully customizable host, something like:
```yaml
backend:
  host: somehost.com:80
```

The first one would be so much easier and more user-friendly for those that route their traffic to the services inside their clusters (most of the cases) and the latter would allow for custom use cases like a different cluster, non-k8s workloads and etc.
