### ISSUE TITLE
Mocking: Return Random Example

### ISSUE THREAD

**Issue by crjones** [kubeshop/kusk-gateway#628]
As a user I want the API to return a different example on each request so I can test a variety of data.

Random will select a random element from the array of examples, If only one example exist it will return that example.
```yaml
  x-kusk:
    mocking:
      enabled: true
      method: random
```
Note this would need to be used with `example` as an array and not `examples`.

```yaml
components:
  schemas:
    ArrayOfUsers:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
      example:
        - id: 10
          name: Jessica Smith
        - id: 20
          name: Ron Stewart
```
