### ISSUE TITLE
Mocking: Return List

### ISSUE THREAD

**Issue by crjones** [kubeshop/kusk-gateway#629]
As a user I want the API to return a list of examples so I can mock a list endpoint.

List will take the `example` array and return it to the user.
```yaml
  x-kusk:
    mocking:
      enabled: true
      method: list
```
Note this would need to be used with `example` as an array and not `examples`.

```yaml
components:
  schemas:
    ArrayOfUsers:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
      example:
        - id: 10
          name: Jessica Smith
        - id: 20
          name: Ron Stewart
```
