### ISSUE TITLE
Mocking: Return by ID

### ISSUE THREAD

**Issue by crjones** [kubeshop/kusk-gateway#630]
As a user I want the API to return a specific element from an array by ID.

List will take the `example` array and return it to the user.
```yaml
  x-kusk:
    mocking:
      enabled: true
      method: match
      parameter: id   # matches a parameter name
      key: id              # matches a key from the example objects
```
Note this would need to be used with `example` as an array and not `examples`.

```yaml
components:
  schemas:
    ArrayOfUsers:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
      example:
        - id: 10
          name: Jessica Smith
        - id: 20
          name: Ron Stewart
```

As an example if mocking was on and parameter value was `10` it would return:
```json
{ "id": 10, "name": "Jessica Smith" }
```

If mocking was on and parameter value was `30` it would return ` 404 - Not Found`
