### ISSUE TITLE
Expose Swagger UI from Kusk

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#654]
Could we host swagger ui for the user and when they add this extension: 
```
x-kusk: 
  playground:
    path: /playground
```
We show them swagger UI under /playground (we could have a default path)

This way consumers can test the API, run operations, etc directly enabled by Kusk

**Comment by crjones** [comment]
Current questions:

- Can this be applied from the OpenAPI spec and still be disabled by removing the playground extension?
- If not, can we apply this through the CLI?

**Comment by aabedraba** [comment]
Work has already started here: https://github.com/kubeshop/kusk-gateway-developer-portal

we need backend tickets for this

**Comment by aabedraba** [comment]
Internal example for Kusk Gateway: 

![Image](https://user-images.githubusercontent.com/27779735/201640986-e8c54d90-3aa8-4b83-ba66-d964be2cd574.png)

**Comment by jasmingacic** [comment]
- [ ] Policy 
```
x-kusk: 
   dev_portal: 
        path: /devportal # user defined path to the devportal
        logo_url:  http://some.url/logo.svg # URL to the logo
        title: some_title # 
```


- [ ] CLI add devportal to cluster installation
- [ ] Add dashboard "Dev Portal settings" 
- [ ] Add more scaffolding to the dev portal UI and dockerize the deployment. DevPortal Backend will based on the devportal route will use kusk API server to detect the API object.
