### ISSUE TITLE
Make `example` folder usable by using end-user configurations

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#702]
Currently, the example folders uses the following configurations: 

```yaml 
fleet:
  name: default
  namespace: default
```
https://github.com/kubeshop/kusk-gateway/blob/main/examples/httpbin/httpbin_v1_api.yaml#L6-L8

This renders the example folder useless for end-users to use because the default end-user configuration is typically: 

```yaml
 fleet:
  name: kusk-gateway-envoy-fleet
  namespace: kusk-system
``` 

Changing all the examples to use end-user configurations would allow for slick experiences where we can just ask people to run the following command to deploy an example API (as opposed to having to copy the file or clone the repo just to deploy an API):

```
kusk deploy -i url-to-github.com
```
