### ISSUE TITLE
API Analytics

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#756]
I would like to be able to specify a GA property which would then be used by Kusk to send operation-level event data to GA - i.e. something in the line of

```
x-kusk:
  analytics:
     google:
        GA-property: UA-129389w84
```

The operationId would be used by default for tracked events - but I should be able to override this at the operation-level using a corresponding x-kusk extension.

Furthermore - I should be able to disable analytics at the path or operation level:

```
x-kusk:
  analytics:
     disabled: true
```
