### ISSUE TITLE
Extension property for target image

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#760]
To help me quickly deploy and expose my APIs without having to learn any k8s configuration yaml I would like to be able to specify everything needed to deploy my API as extension properties at the root level. For example:

```
x-kusk:
   deployment:
      image: swaggerapi/petstore3:unstable
      port: 8080
```

When deploying, Kusk would create both Deployment and Service resources in my cluster which would be the upstream service for my Kusk deployment.

I know this is going beyond the current scope - but I wanted to capture it anyway, since it greatly simplifies the onboarding journey for developers having to deploy their services to K8s

**Comment by aabedraba** [comment]
Love it! 

Although I'd still keep it under `upstream` for predictability's sake
```
x-kusk:
  upstream: 
    deployment:
      image: swaggerapi/petstore3:unstable
      port: 8080
```
