### ISSUE TITLE
Upstream authorization

### ISSUE THREAD

**Issue by jasmingacic** [kubeshop/kusk-gateway#807]
As a user I want to be able to access upstreams or hostnames that require authentication. 
```
x-kusk:
   upstream: # routes the POST /pet endpoint to a Kubernetes service
      service:
         namespace: default
         name: petstore
         port: 8000
         bearerToken: xxx ## or any type of auth user might come across 
```

**Comment by aabedraba** [comment]
Perhaps this should have an entire object dedicated for it... 
```yaml
x-kusk:
   upstream: # routes the POST /pet endpoint to a Kubernetes service
      service:
         namespace: default
         name: petstore
         port: 8000
         auth:
           ...
```
