### ISSUE TITLE
Changes to Kusk Policy

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#837]
Proposal to change the API of the Kusk Policy

## Auth Policies 

Generally removing the `scheme` object and making it more relevant to the specific provider: 

**Cloudentity**
```yaml
# FROM 
x-kusk:
  auth:
    scheme: cloudentity
    auth-upstream:
      host:
        hostname: cloudentity-authorizer-standalone-authorizer.kusk-system
        port: 9004

# TO
x-kusk:
  auth:
    cloudentity:
      host:
        hostname: cloudentity-authorizer-standalone-authorizer.kusk-system
        port: 9004
```

**Basic auth:**

```yaml
# Basic -> Rename to custom-upstream
# FROM 
x-kusk:
  auth:
    scheme: basic
    path_prefix: /login # optional
    auth-upstream:
      host:
        hostname: example.com
        port: 80

# TO
x-kusk:
  auth:
    custom:
      host:
        hostname: example.com
        port: 80
```

**OAuth2**

```yaml
# OAuth2
# FROM 
x-kusk:
  auth:
    scheme: oauth2
    oauth2:
      token_endpoint: *TOKEN_ENDPOINT* # <- for example https://yourdomain.eu.auth0.com/oauth/token
      authorization_endpoint: *AUTHORIZATION_ENDPOINT* # <- for example https://yourdomain.eu.auth0.com/authorize
      credentials:
        client_id: *CLIENT_ID*
        client_secret: *CLIENT_SECRET*
      redirect_uri: /oauth2/callback
      redirect_path_matcher: /oauth2/callback
      signout_path: /oauth2/signout
      forward_bearer_token: true
      auth_scopes:
        - openid

# TO 
x-kusk:
  auth:
    oauth2:
      token_endpoint: *TOKEN_ENDPOINT* # <- for example https://yourdomain.eu.auth0.com/oauth/token
      authorization_endpoint: *AUTHORIZATION_ENDPOINT* # <- for example https://yourdomain.eu.auth0.com/authorize
      credentials:
        client_id: *CLIENT_ID*
        client_secret: *CLIENT_SECRET*
      redirect_uri: /oauth2/callback
      redirect_path_matcher: /oauth2/callback
      signout_path: /oauth2/signout
      forward_bearer_token: true
      auth_scopes:
        - opened
```

## Non-Auth Policies: 

**Exposing OpenAPI API**
```yaml
# FROM 
x-kusk:
  openapi-path: openapi.json

# TO
x-kusk: 
  public_api_path: /openapi
```

**Disabled**: change to hidden, which reflects what it's actually doing
```yaml
# FROM 
/path:
  x-kusk:
    disabled: true
# TO 
/path:
  x-kusk:
    hidden: true
```

**Comment by mbana** [comment]
> **Basic auth:**
> 
> ```yaml
> # Basic -> Rename to custom-upstream
> # FROM 
> x-kusk:
>   auth:
>     scheme: basic
>     path_prefix: /login # optional
>     auth-upstream:
>       host:
>         hostname: example.com
>         port: 80
> 
> # TO
> x-kusk:
>   auth:
>     custom-upstream:
>       hostname: example.com
>       port: 80
> ```

I'd prefer to use:

```yaml
x-kusk:
  auth:
    ext-authz:
      uri: https://example.com
      port: 80
```

```yaml
x-kusk:
  auth:
    ext-authz:
      uri: https://example.com
```

`uri`: The HTTP server URI. It should be a full FQDN with protocol, host and path.
