### ISSUE TITLE
Enable access to Developer Portal through the default EnvoyFleet

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#867]
Relates to https://github.com/kubeshop/kusk-gateway/issues/654

We could do it through a kusk extension: 

GIVEN 
```yaml 
x-kusk:
  developer-portal:
    path: portal
    favicon_url: url.com
    title (optional): Title of my API 
```
THEN
When visiting `mydomain.com/portal`, the developer portal should be shown
