### ISSUE TITLE
StaticRoute restructure

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#869]
Static Routes allow creating different paths like the following: 

```yaml
apiVersion: gateway.kusk.io/v1alpha1
kind: StaticRoute
metadata:
  name: sample
spec:
  fleet:
    name: kusk-gateway-envoy-fleet
    namespace: kusk-system
  paths:
    /: # <-- frontend path
      get: 
        route: &root_route
          upstream:
            service:
              name: frontend-app-svc
              namespace: default
              port: 3000 
```

but usually when deploying a frontend, popular frameworks like react and nextjs create many requests that are not included in the described path, for example: 

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/27779735/195583752-7497c6b8-ed09-451b-95e1-30aea64418ae.png">

Perhaps we could move to top level extensions? For example: 

```yaml
apiVersion: gateway.kusk.io/v1alpha1
kind: StaticRoute
metadata:
  name: sample
spec:
  fleet:
    name: kusk-gateway-envoy-fleet
    namespace: kusk-system
  upstream:
    service:
      name: frontend-app-svc
      namespace: default
      port: 3000
```

And while we're on it, could we maybe change the name `StaticRoute` which is very undescriptive of this feature that frontenders use to something more common like "Pages" (this is just an option I saw pretty much used by [github](https://pages.github.com/) and [cloudeflare](https://pages.cloudflare.com/))? Open to suggestions.
