### ISSUE TITLE
Manager - resources limitations

### ISSUE THREAD

**Issue by jasmingacic** [kubeshop/kusk-gateway#905]
What was the reasoning behind these limitations?

https://github.com/kubeshop/kusk-gateway/blob/main/config/manager/manager.yaml#L48-L54
```
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 256Mi
```
