### ISSUE TITLE
Canary deployment

### ISSUE THREAD

**Issue by jasmingacic** [kubeshop/kusk-gateway#937]
Ability to redirect traffic from one route based on matched headers:

Envoy Config example:
```
routes:
- match:
    prefix: "/service/v1"
    headers:
      - name: "x-canary"
        value: "upstreamV2"
  route:
    cluster: upstreamV1
- match:
    prefix: "/service/v1"
  route:
    cluster: upstreamV1
- match:
    prefix: "/service/v2"
  route:
    cluster: upstreamV2
```

Header based depending on header passed in the request kusk would redirect to the defined upstream service. In this example:
`curl 0.0.0.0/service/v1` it will redirect to upstreamV1
`curl -H 'x-canary: upstreamV2' 0.0.0.0/service/v1` it will redirect to upstreamV2
Route based is very simple:
`curl 0.0.0.0/service/v2`-> upstreamV2

Additional control could be performed by introductions of Lua or WASM filters.
