### ISSUE TITLE
Housekeeping: Kusk Services

### ISSUE THREAD

**Issue by jasmingacic** [kubeshop/kusk-gateway#956]
The [service](https://github.com/kubeshop/kusk-gateway/blob/main/config/manager/service.yaml#L31-L45) created with each kusk installation should be done programmatically  [here](https://github.com/kubeshop/kusk-gateway/blob/main/internal/envoy/auth/ext_authz_parser.go#L47-L48).

Challenge: Since `kusk-gateway-auth-service` is only used when Cloudentity is configured we need to find a way of knowing when to remove the service if unused. Reconciler doesn't have any knowledge of the previous state of the cluster.

**Comment by aabedraba** [comment]
Finding a way to deal with unused resources and automatically cleaning them up should be of big value regarding clunkiness of our installation.

Currently we have: 

Absolutely necessary: 

- kusk-gateway-validator-service
- kusk-gateway-webhooks-service
- kusk-gateway-xds-service
- kusk-gateway-envoy-fleet
- kusk-gateway-manager-metrics-service

Only necessary with specific features: 
- kusk-gateway-api (for dashboard)
**- kusk-gateway-auth-service (for cloudentity)**
- kusk-gateway-dashboard (for dashboard)
- kusk-gateway-private-envoy-fleet (for dashboard)

Soon we'll also probably have:
**- kusk-gateway-developer-portal (for developer portal)**
**- kusk-gateway-mocking (potentially?? for gateway-level mocking)**

The services/deployments marked in bold should only be in the cluster if the feature is in used, i.e. in the case of developer portal, it should only be there if the user adds the corresponding x-kusk policy to the OpenAPI definition.

**Potential solutions:**
- Users run a CLI command `kusk enable developer-portal` `kusk enable mocking` to add remove these services from the cluster
- Kusk manager/reconciler creates/deletes resources every time a new definition is applied
- We continue bloating it as it is (maybe the pods aren't thaaaat big)... and tackle this later on

**Comment by jasmingacic** [comment]
Solution:

Currently we have this sort of setup https://github.com/kubeshop/kusk-gateway/blob/main/config/manager/service.yaml
In short three services that are pointing to the same selector but on diferent paths.  It should be extracted into something like this
```
apiVersion: v1
kind: Service
metadata:
  name: kusk-gateway-manager-service
  namespace: system
  labels:
    app.kubernetes.io/component: kusk-manager
spec:
  ports:
    - port: 18000
      name: xds
      targetPort: xds
    - port: 17000
      name: validator
      targetPort: validator
   - port: 19000
      name: auth
      targetPort: auth
      protocol: TCP
  selector:
    app.kubernetes.io/component: kusk-gateway-manager
```
